/*
 * Copyright (C) 2022-2026 Amalgam Solucoes em TI Ltda.
 * SPDX-License-Identifier: Apache-2.0
 */

import {readFileSync} from 'fs';
import * as path from 'path';
import {MavenTotalCrossProject} from './maven-project';

export interface RenderedGradleProject {
    files: Map<string, Buffer | string>;
    sensitiveFiles: string[];
}

const TEMPLATE_ROOT = path.resolve(__dirname, '..', '..', 'resources', 'gradle');
const DEFAULT_REPOSITORY = 'https://maven.totalcross.com/artifactory/repo1';
const MARKER = '// Generated by TotalCross Maven-to-Gradle migration.';

function quote(value: string): string {
    return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function repositoryBlock(url: string): string {
    const insecure = /^http:\/\//i.test(url) ? '\n        allowInsecureProtocol = true' : '';
    return `    maven {\n        url = uri('${quote(url)}')${insecure}\n    }`;
}

function totalcrossLine(name: string, value: string | undefined): string {
    return value ? `    ${name} = file('${quote(value)}')\n` : '';
}

function wrapper(relative: string): Buffer {
    return readFileSync(path.join(TEMPLATE_ROOT, relative));
}

/** Renders a Groovy Gradle build plus wrapper and non-secret migration metadata. */
export function renderGradleProject(project: MavenTotalCrossProject, pluginVersion: string): RenderedGradleProject {
    const repositories = project.repositories.length ? project.repositories : [DEFAULT_REPOSITORY];
    const javaRelease = project.javaRelease || (/^7\.(?:[3-9]|[1-9]\d)\./.test(project.sdkVersion) || /^([89]|[1-9]\d)\./.test(project.sdkVersion) ? 17 : 8);
    const platforms = project.platforms.map((platform) => `'${quote(platform)}'`).join(', ');
    const files = new Map<string, Buffer | string>();
    files.set('settings.gradle', `${MARKER}\npluginManagement {\n    repositories {\n        mavenLocal()\n        gradlePluginPortal()\n        mavenCentral()\n    }\n}\n\nrootProject.name = '${quote(project.artifactId)}'\n`);
    files.set('build.gradle', `${MARKER}\nplugins {\n    id 'java'\n    id 'com.totalcross.application' version '${quote(pluginVersion)}'\n}\n\ngroup = '${quote(project.groupId || 'com.totalcross')}'\nversion = '${quote(project.version || '1.0-SNAPSHOT')}'\n\nrepositories {\n${repositories.map(repositoryBlock).join('\n')}\n    mavenCentral()\n}\n\njava {\n    toolchain { languageVersion = JavaLanguageVersion.of(17) }\n}\n\ntasks.withType(JavaCompile).configureEach { options.release = ${javaRelease} }\n\ndependencies {\n    implementation 'com.totalcross:totalcross-sdk:${quote(project.sdkVersion)}'\n}\n\ntotalcross {\n    applicationName = '${quote(project.applicationName)}'\n    platforms = [${platforms}]\n    activationKey = providers.gradleProperty('totalcrossActivationKey').orNull\n${totalcrossLine('certificates', project.certificates)}${totalcrossLine('totalcrossHome', project.totalcrossHome)}}\n`);
    files.set('.totalcross/project.json', JSON.stringify({buildSystem: 'gradle', artifactId: project.artifactId, applicationName: project.applicationName, sdkVersion: project.sdkVersion}, null, 2) + '\n');
    files.set('gradlew', wrapper('gradlew'));
    files.set('gradlew.bat', wrapper('gradlew.bat'));
    files.set('gradle/wrapper/gradle-wrapper.jar', wrapper('gradle/wrapper/gradle-wrapper.jar'));
    files.set('gradle/wrapper/gradle-wrapper.properties', wrapper('gradle/wrapper/gradle-wrapper.properties'));
    const sensitiveFiles: string[] = [];
    if (project.activationKey) {
        files.set('gradle.properties', `totalcrossActivationKey=${project.activationKey}\n`);
        sensitiveFiles.push('gradle.properties');
    }
    return {files, sensitiveFiles};
}

export const GENERATED_GRADLE_MARKER = MARKER;
