/*
 * Copyright (C) 2022-2026 Amalgam Solucoes em TI Ltda.
 * SPDX-License-Identifier: Apache-2.0
 */

import * as assert from 'assert';
import {promises as fs} from 'fs';
import * as os from 'os';
import * as path from 'path';
import {writeAndValidateGradleProject} from '../../migration/convert-project';

suite('Maven to Gradle conversion transaction', () => {
    test('preserves the POM only after successful validation and keeps unrelated properties', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-convert-success-'));
        try {
            await fs.writeFile(path.join(root, 'pom.xml'), '<project/>');
            await fs.writeFile(path.join(root, 'gradle.properties'), 'other=value\n');
            const files = new Map<string, Buffer | string>();
            files.set('build.gradle', '// Generated by TotalCross Maven-to-Gradle migration.\n');
            files.set('gradlew', '#!/bin/sh\n');
            files.set('gradle.properties', 'totalcrossActivationKey=secret\n');
            const result = await writeAndValidateGradleProject(root, {files, sensitiveFiles: ['gradle.properties']}, () => Promise.resolve());
            assert.equal(result, 'converted');
            assert.equal(await exists(path.join(root, 'pom.xml')), false);
            assert.equal(await exists(path.join(root, 'pom.xml.maven-backup')), true);
            assert.equal(await fs.readFile(path.join(root, 'gradle.properties'), 'utf8'), 'other=value\ntotalcrossActivationKey=secret\n');
        } finally { await fs.rmdir(root, {recursive: true}); }
    });

    test('restores modified files after validation failure', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-convert-rollback-'));
        try {
            await fs.writeFile(path.join(root, 'pom.xml'), '<project/>');
            await fs.writeFile(path.join(root, 'build.gradle'), 'original');
            const files = new Map<string, Buffer | string>();
            files.set('build.gradle', 'replacement');
            await assert.rejects(writeAndValidateGradleProject(root, {files, sensitiveFiles: []}, () => Promise.reject(new Error('validation failed'))), /validation failed/);
            assert.equal(await fs.readFile(path.join(root, 'build.gradle'), 'utf8'), 'original');
            assert.equal(await exists(path.join(root, 'pom.xml')), true);
        } finally { await fs.rmdir(root, {recursive: true}); }
    });

    test('keeps generated files and the POM when Maven Local lacks the plugin', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'totalcross-convert-local-plugin-'));
        try {
            await fs.writeFile(path.join(root, 'pom.xml'), '<project/>');
            const files = new Map<string, Buffer | string>();
            files.set('build.gradle', 'generated');
            const result = await writeAndValidateGradleProject(root, {files, sensitiveFiles: []}, () => Promise.reject(new Error('Could not resolve com.totalcross.application plugin: not found')));
            assert.equal(result, 'plugin-not-local');
            assert.equal(await fs.readFile(path.join(root, 'build.gradle'), 'utf8'), 'generated');
            assert.equal(await exists(path.join(root, 'pom.xml')), true);
        } finally { await fs.rmdir(root, {recursive: true}); }
    });
});

async function exists(file: string): Promise<boolean> { try { await fs.access(file); return true; } catch (_) { return false; } }
